# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14D-S-o4-GCbPKe2yiCPtD1MNF4v6UuL2
"""

import streamlit as st

# Título da aplicação
st.title('Minha Primeira Aplicação Streamlit')

# Subtítulo
st.header('Introdução')

# Texto
st.write('Olá, mundo! Esta é a minha primeira aplicação utilizando Streamlit.')

# Entrada de texto
nome = st.text_input('Digite seu nome:')
if nome:
    st.write(f'Olá, {nome}!')

# Slider
idade = st.slider('Selecione sua idade:', 0, 100, 25)
st.write(f'Sua idade é {idade} anos.')

# Gráfico simples
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure()
plt.plot(x, y)
st.pyplot(plt)

# Botão
if st.button('Clique aqui'):
    st.write('Você clicou no botão!')

# Checkbox
if st.checkbox('Marque este checkbox'):
    st.write('Checkbox marcado!')

# Seletor de opção
opcao = st.selectbox('Escolha uma opção:', ['Opção 1', 'Opção 2', 'Opção 3'])
st.write(f'Você escolheu: {opcao}')

streamlit run app.py